# -*- coding: utf-8 -*-

from typing import Final

CVP_NO_DOTENV: Final[str] = "CVP_NO_DOTENV"
CVP_DOTENV_PATH: Final[str] = "CVP_NO_DOTENV"

CVP_HOME: Final[str] = "CVP_HOME"

CVP_COLORED_LOGGING: Final[str] = "CVP_COLORED_LOGGING"
CVP_DEFAULT_LOGGING: Final[str] = "CVP_DEFAULT_LOGGING"
CVP_SIMPLE_LOGGING: Final[str] = "CVP_SIMPLE_LOGGING"
CVP_ROTATE_LOGGING_PREFIX: Final[str] = "CVP_ROTATE_LOGGING_PREFIX"
CVP_ROTATE_LOGGING_WHEN: Final[str] = "CVP_ROTATE_LOGGING_WHEN"

CVP_SEVERITY: Final[str] = "CVP_SEVERITY"
CVP_DEBUG: Final[str] = "CVP_DEBUG"
CVP_VERBOSE: Final[str] = "CVP_VERBOSE"
